print("O objetivo deste código é calcular a quantidade de tinta necessária para um parede.")
print("")
L = float(input("Qual é a largura dessa parede? "))
H = float(input("Qual é a altura dessa parede? "))
print("")
A = (L*H)
print(f"A área dessa parede é {A:.2f} centímetros quadrados.")
Q = (A/2)
print(f"É necessário {Q:.2f} litros de tinta.")
